LANGUAGE_ITEMS = (
    ("EN", "English", "Use English labels in the add-on interface"),
    ("RU", "Русский", "Использовать русские подписи в интерфейсе аддона"),
)


TEXT = {
    "EN": {
        "language": "Language",
        "main_description": "Semi-automatic retopology tools for generated AI meshes",
        "section_import": "Import",
        "section_batch_import": "Batch Import",
        "section_model_preparation": "Model Preparation",
        "section_seam_preparation": "Seam Preparation",
        "section_polygroups": "PolyGroups",
        "section_remesh": "Remesh",
        "section_resculpting": "Resculpting",
        "section_seam_finalization": "Seam Finalization",
        "section_baking": "Baking",
        "section_ai_generation": "AI Generation",
        "openai_image": "OpenAI Image",
        "google_image": "Google Image",
        "use_env_openai_api_key": "Use OPENAI_API_KEY",
        "openai_api_key": "OpenAI API Key",
        "use_env_gemini_api_key": "Use GEMINI_API_KEY",
        "gemini_api_key": "Google Gemini API Key",
        "updates": "Updates",
        "check_updates": "Check Updates",
        "update_addon": "Update",
        "update_status": "Status: {value}",
        "update_commits": "Branch: {branch} | Local: {current} | Remote: {remote}",
        "update_last_checked": "Last checked: {value}",
        "rename_apply_weld": "Rename And Apply Weld",
        "rename_objects": "Rename Objects",
        "weld_distance": "Weld Distance",
        "apply_weld": "Apply Weld",
        "import_files": "Import Files",
        "format": "Format",
        "auto_rename_objects": "Auto Rename Objects",
        "folder": "Folder:",
        "no_folder_selected": "No folder selected",
        "total_files": "Total Files: {value}",
        "imported_files": "Imported Files: {value}",
        "imported_objects": "Imported Objects: {value}",
        "remaining_files": "Remaining Files: {value}",
        "current_file": "Current: {value}",
        "scan_folder": "Scan Folder",
        "import_folder": "Import Folder",
        "quad_not_installed": "Quad Remesher add-on is not installed.",
        "quad_install_hint": "Install it to use these controls.",
        "quad_not_enabled": "Quad Remesher add-on is installed but not enabled.",
        "quad_enable_hint": "Enable it in Blender Preferences.",
        "quad_available": "Uses the installed Quad Remesher add-on.",
        "remesh_it": "Remesh It",
        "quad_count": "Quad Count",
        "use_materials": "Use Materials",
        "symmetry": "Symmetry:",
        "smooth_iterations": "Smooth Iterations",
        "smooth_face_selection": "Smooth Face Selection",
        "mark_selected_edges_seam": "Mark Selected Edges Seam",
        "mark_selection_boundary_seam": "Mark Selection Boundary Seam",
        "knife_seam": "Knife Seam",
        "quick_knife_seam": "Quick Knife Seam",
        "object_seam_cutter": "Object Seam Cutter",
        "stable_view_cut": "Stable View Cut",
        "xray": "X-Ray",
        "occlude_geometry": "Occlude Geometry",
        "only_selected": "Only Selected",
        "mark_as_seam": "Mark As Seam",
        "clear_selection_after_cutting": "Clear Selection After Cutting",
        "select_knife_tool": "Select Knife Seam Tool",
        "select_quick_knife_tool": "Select Quick Knife Seam Tool",
        "fill": "Fill",
        "threshold": "Threshold",
        "cutter_size": "Cutter Size",
        "cylinder_segments": "Cylinder Segments",
        "cutter_alpha": "Cutter Alpha",
        "plane_thickness": "Plane Thickness",
        "path_render_u": "Path Render U",
        "path_extrude": "Path Extrude",
        "path_tilt_step": "Path Tilt Step",
        "ctrl_draw_hint": "Ctrl + Click Draw",
        "hide_cutters_after_apply": "Hide Cutters After Apply",
        "delete_cutters_after_apply": "Delete Cutters After Apply",
        "select_draw_cutter_plane": "Select Draw Cutter Plane Tool",
        "draw_cutter_plane": "Draw Cutter Plane",
        "select_draw_cutter_arc": "Select Draw Cutter Arc Tool",
        "draw_cutter_arc": "Draw Cutter Arc",
        "select_draw_cutter_path": "Select Draw Cutter Path Tool",
        "draw_cutter_path": "Draw Cutter Path",
        "tilt_minus": "Tilt -",
        "tilt_plus": "Tilt +",
        "tilt_reset": "Reset Tilt",
        "apply_cutter_seams": "Apply Cutter Seams To Active",
        "select": "Select",
        "clear": "Clear",
        "last_cutters": "Last Cutters: {value}",
        "last_seam_edges": "Last Seam Edges: {value}",
        "material_mode": "Material Mode",
        "checker_scale": "Checker Scale",
        "generate_polygroups": "Generate PolyGroups",
        "apply_material_mode": "Apply Material Mode",
        "apply_checker_material": "Apply Checker Material",
        "generate_seams_materials": "Generate Seams From Materials",
        "unwrap_angle_based": "Unwrap Angle Based",
        "face_sets_to_materials": "Face Sets To Materials",
        "clear_polygroups_materials": "Clear PolyGroups Materials",
        "auto_unwrap": "Auto Unwrap",
        "create_longitudinal_seam": "Create Longitudinal Seam",
        "boundary_longitudinal_seam": "Boundary + Longitudinal Seam",
        "smart_uv_project": "Smart UV Project",
        "average_islands_scale": "Average Islands Scale",
        "bake_resolution": "Bake Resolution",
        "bake_margin": "Bake Margin",
        "cage_extrusion": "Cage Extrusion",
        "ray_distance": "Ray Distance",
        "image_prefix": "Image Prefix",
        "selected_to_active": "Selected To Active",
        "base_color": "Base Color",
        "normal": "Normal",
        "check_material_textures": "Check Material/Textures",
        "prepare_highpoly_texture_only": "Prepare Highpoly Texture Only",
        "prepare_lowpoly_bake_material": "Prepare Lowpoly Bake Material",
        "bake_selected_to_active": "Bake Selected To Active",
        "prepare_and_bake": "Prepare And Bake",
        "save_textures": "Save Textures",
        "merge_materials_textures": "Merge Materials/Textures",
        "clear_all_bake_images": "Clear All Bake Images",
        "multires_levels": "Multires Levels",
        "shrinkwrap_limit": "Shrinkwrap Limit",
        "shrinkwrap_offset": "Shrinkwrap Offset",
        "setup_resculpting": "Setup Resculpting",
        "multires": "Multires",
        "shrinkwrap": "Shrinkwrap",
        "material_source_texture": "Source Texture",
        "material_texture_color": "Texture + Color",
        "material_random_color": "Random Color",
        "material_checker_texture": "Checker Texture",
        "format_auto": "Auto",
        "ai_prompt": "Prompt",
        "ai_model": "Model",
        "ai_size": "Size",
        "ai_quality": "Quality",
        "ai_aspect_ratio": "Aspect Ratio",
        "ai_image_size": "Image Size",
        "ai_output_format": "Output Format",
        "ai_input_image": "Input Image",
        "select_base_color_image": "Select Base Color Image",
        "select_normal_map_image": "Select Normal Map Image",
        "preview_input_image": "Preview Input",
        "generate_openai_image": "Generate OpenAI Image",
        "generate_google_image": "Generate Google Image",
        "open_image_editor": "Open In Image Editor",
        "save_image": "Save Image",
        "ai_status": "Status: {value}",
        "ai_last_image": "Last Image: {value}",
        "ai_no_status": "Ready",
        "ai_key_missing": "OpenAI API key is missing. Add it in preferences or set OPENAI_API_KEY.",
        "google_key_missing": "Google Gemini API key is missing. Add it in preferences or set GEMINI_API_KEY.",
        "ai_generating": "Generating image...",
        "prompt_library": "Prompt Library",
        "prompt_collection": "Collection",
        "prompt_file": "Prompt",
        "load_to_openai": "Load OpenAI",
        "load_to_google": "Load Google",
        "load_to_both": "Load Both",
        "append_to_openai": "Append OpenAI",
        "append_to_google": "Append Google",
        "refresh_prompt_library": "Refresh",
        "open_prompt_folder": "Open Folder",
    },
    "RU": {
        "language": "Язык",
        "main_description": "Инструменты полуавтоматической ретопологии для AI-мешей",
        "section_import": "Импорт",
        "section_batch_import": "Пакетный импорт",
        "section_model_preparation": "Подготовка модели",
        "section_seam_preparation": "Подготовка швов",
        "section_polygroups": "Полигруппы",
        "section_remesh": "Ремеш",
        "section_resculpting": "Рескульптинг",
        "section_seam_finalization": "Финализация швов",
        "section_baking": "Бейкинг",
        "section_ai_generation": "AI-генерация",
        "openai_image": "OpenAI Image",
        "google_image": "Google Image",
        "use_env_openai_api_key": "Использовать OPENAI_API_KEY",
        "openai_api_key": "OpenAI API Key",
        "use_env_gemini_api_key": "Использовать GEMINI_API_KEY",
        "gemini_api_key": "Google Gemini API Key",
        "updates": "Обновления",
        "check_updates": "Проверить обновления",
        "update_addon": "Обновить",
        "update_status": "Статус: {value}",
        "update_commits": "Ветка: {branch} | Локально: {current} | Удаленно: {remote}",
        "update_last_checked": "Последняя проверка: {value}",
        "rename_apply_weld": "Переименовать и применить Weld",
        "rename_objects": "Переименовать объекты",
        "weld_distance": "Дистанция Weld",
        "apply_weld": "Применить Weld",
        "import_files": "Импорт файлов",
        "format": "Формат",
        "auto_rename_objects": "Автопереименование",
        "folder": "Папка:",
        "no_folder_selected": "Папка не выбрана",
        "total_files": "Всего файлов: {value}",
        "imported_files": "Импортировано файлов: {value}",
        "imported_objects": "Импортировано объектов: {value}",
        "remaining_files": "Осталось файлов: {value}",
        "current_file": "Текущий: {value}",
        "scan_folder": "Сканировать папку",
        "import_folder": "Импорт папки",
        "quad_not_installed": "Аддон Quad Remesher не установлен.",
        "quad_install_hint": "Установите его, чтобы использовать эти функции.",
        "quad_not_enabled": "Аддон Quad Remesher установлен, но не включен.",
        "quad_enable_hint": "Включите его в настройках Blender.",
        "quad_available": "Используется установленный аддон Quad Remesher.",
        "remesh_it": "Запустить ремеш",
        "quad_count": "Количество квадов",
        "use_materials": "Использовать материалы",
        "symmetry": "Симметрия:",
        "smooth_iterations": "Итерации сглаживания",
        "smooth_face_selection": "Сгладить выделение фейсов",
        "mark_selected_edges_seam": "Пометить выделенные ребра как швы",
        "mark_selection_boundary_seam": "Шов по границе выделения",
        "knife_seam": "Knife Seam",
        "quick_knife_seam": "Quick Knife Seam",
        "object_seam_cutter": "Object Seam Cutter",
        "stable_view_cut": "Стабильный рез из вида",
        "xray": "X-Ray",
        "occlude_geometry": "Только видимая геометрия",
        "only_selected": "Только выделенное",
        "mark_as_seam": "Пометить как шов",
        "clear_selection_after_cutting": "Снять выделение после реза",
        "select_knife_tool": "Выбрать Knife Seam",
        "select_quick_knife_tool": "Выбрать Quick Knife Seam",
        "fill": "Заполнить",
        "threshold": "Порог",
        "cutter_size": "Размер каттера",
        "cylinder_segments": "Сегменты цилиндра",
        "cutter_alpha": "Прозрачность каттера",
        "plane_thickness": "Толщина плоскости",
        "path_render_u": "Render U пути",
        "path_extrude": "Толщина пути",
        "path_tilt_step": "Шаг Tilt пути",
        "ctrl_draw_hint": "Ctrl + Click рисует",
        "hide_cutters_after_apply": "Скрыть каттеры после применения",
        "delete_cutters_after_apply": "Удалить каттеры после применения",
        "select_draw_cutter_plane": "Выбрать Draw Cutter Plane",
        "draw_cutter_plane": "Нарисовать cutter plane",
        "select_draw_cutter_arc": "Выбрать Draw Cutter Arc",
        "draw_cutter_arc": "Нарисовать cutter arc",
        "select_draw_cutter_path": "Выбрать Draw Cutter Path",
        "draw_cutter_path": "Нарисовать cutter path",
        "tilt_minus": "Tilt -",
        "tilt_plus": "Tilt +",
        "tilt_reset": "Сбросить Tilt",
        "apply_cutter_seams": "Применить cutter seams к активному",
        "select": "Выбрать",
        "clear": "Очистить",
        "last_cutters": "Последние каттеры: {value}",
        "last_seam_edges": "Последние швы: {value}",
        "material_mode": "Режим материала",
        "checker_scale": "Масштаб checker",
        "generate_polygroups": "Сгенерировать полигруппы",
        "apply_material_mode": "Применить режим материалов",
        "apply_checker_material": "Применить checker material",
        "generate_seams_materials": "Создать швы по материалам",
        "unwrap_angle_based": "Развертка Angle Based",
        "face_sets_to_materials": "Face Sets в материалы",
        "clear_polygroups_materials": "Очистить материалы полигрупп",
        "auto_unwrap": "Авторазвертка",
        "create_longitudinal_seam": "Создать продольный шов",
        "boundary_longitudinal_seam": "Граница + продольный шов",
        "smart_uv_project": "Smart UV Project",
        "average_islands_scale": "Выровнять масштаб островов",
        "bake_resolution": "Разрешение bake",
        "bake_margin": "Отступ bake",
        "cage_extrusion": "Cage Extrusion",
        "ray_distance": "Ray Distance",
        "image_prefix": "Префикс изображений",
        "selected_to_active": "Selected To Active",
        "base_color": "Base Color",
        "normal": "Normal",
        "check_material_textures": "Проверить материалы/текстуры",
        "prepare_highpoly_texture_only": "Highpoly в Texture Only",
        "prepare_lowpoly_bake_material": "Подготовить материал lowpoly",
        "bake_selected_to_active": "Запечь выделенное на активный",
        "prepare_and_bake": "Подготовить и запечь",
        "save_textures": "Сохранить текстуры",
        "merge_materials_textures": "Объединить материалы/текстуры",
        "clear_all_bake_images": "Очистить все bake images",
        "multires_levels": "Уровни Multires",
        "shrinkwrap_limit": "Лимит Shrinkwrap",
        "shrinkwrap_offset": "Смещение Shrinkwrap",
        "setup_resculpting": "Настроить рескульптинг",
        "multires": "Multires",
        "shrinkwrap": "Shrinkwrap",
        "material_source_texture": "Исходная текстура",
        "material_texture_color": "Текстура + цвет",
        "material_random_color": "Случайный цвет",
        "material_checker_texture": "Checker Texture",
        "format_auto": "Авто",
        "ai_prompt": "Промпт",
        "ai_model": "Модель",
        "ai_size": "Размер",
        "ai_quality": "Качество",
        "ai_aspect_ratio": "Соотношение сторон",
        "ai_image_size": "Размер изображения",
        "ai_output_format": "Формат",
        "ai_input_image": "Input Image",
        "select_base_color_image": "Выбрать Base Color Image",
        "select_normal_map_image": "Выбрать Normal Map Image",
        "preview_input_image": "Preview Input",
        "generate_openai_image": "Сгенерировать OpenAI изображение",
        "generate_google_image": "Сгенерировать Google изображение",
        "open_image_editor": "Открыть в Image Editor",
        "save_image": "Сохранить изображение",
        "ai_status": "Статус: {value}",
        "ai_last_image": "Последнее изображение: {value}",
        "ai_no_status": "Готово",
        "ai_key_missing": "OpenAI API key не найден. Добавьте его в настройках или задайте OPENAI_API_KEY.",
        "google_key_missing": "Google Gemini API key не найден. Добавьте его в настройках или задайте GEMINI_API_KEY.",
        "ai_generating": "Генерация изображения...",
        "prompt_library": "Библиотека промптов",
        "prompt_collection": "Коллекция",
        "prompt_file": "Промпт",
        "load_to_openai": "Загрузить OpenAI",
        "load_to_google": "Загрузить Google",
        "load_to_both": "Загрузить в обе",
        "append_to_openai": "Добавить OpenAI",
        "append_to_google": "Добавить Google",
        "refresh_prompt_library": "Обновить",
        "open_prompt_folder": "Открыть папку",
    },
}


def get_preferences(context):
    if context is None:
        return None

    addon = context.preferences.addons.get(__package__)
    if addon is None:
        return None
    return addon.preferences


def get_language(context):
    preferences = get_preferences(context)
    if preferences is None:
        return "EN"
    return getattr(preferences, "interface_language", "EN")


def t(context, key, **kwargs):
    language = get_language(context)
    value = TEXT.get(language, TEXT["EN"]).get(key, TEXT["EN"].get(key, key))
    if kwargs:
        return value.format(**kwargs)
    return value
