LANGUAGE_ITEMS = (
    ("EN", "English", "Use English labels in the add-on interface"),
    ("RU", "Русский", "Использовать русские подписи в интерфейсе аддона"),
)


TEXT = {
    "EN": {
        "language": "Language",
        "main_description": "Semi-automatic retopology tools for generated AI meshes",
        "preferences_info": "Info",
        "preferences_language": "Language Settings",
        "preferences_operations": "Operations",
        "preferences_api": "API",
        "preferences_pie_menu": "Pie Menu Settings",
        "addon_name": "Name: {value}",
        "addon_version": "Version: {value}",
        "addon_author": "Author: {value}",
        "addon_contact": "Contact: {value}",
        "addon_github": "GitHub: {value}",
        "open_link": "Open",
        "show_panel_settings": "Show Panel Settings",
        "play_sound_after_operations": "Play sound after operations",
        "section_import": "Import",
        "section_batch_import": "Batch Import",
        "section_model_preparation": "Model Preparation",
        "section_seam_preparation": "Seam Preparation",
        "section_polygroups": "PolyGroups",
        "section_remesh": "Remesh",
        "section_resculpting": "Resculpting",
        "section_seam_finalization": "Seam Finalization",
        "section_uv_preparation": "UV Preparation",
        "section_baking": "Baking",
        "section_ai_generation": "AI Generation",
        "section_mesh_finalization": "Mesh Finalization",
        "section_render": "Render",
        "openai_image": "OpenAI Image",
        "google_image": "Google Image",
        "use_env_openai_api_key": "Use OPENAI_API_KEY",
        "openai_api_key": "OpenAI API Key",
        "use_env_gemini_api_key": "Use GEMINI_API_KEY",
        "gemini_api_key": "Google Gemini API Key",
        "hotkeys": "Hotkeys",
        "cutter_tweak_tool": "Cutter Tweak Start Tool",
        "enable_cutter_tweak_hotkey": "Enable Cutter Tweak Hotkey",
        "enable_pie_menu_hotkey": "Enable Pie Menu Hotkey",
        "hotkey_key": "Key",
        "pie_menu_slots": "Pie Menu Slots",
        "pie_slot": "Slot {index}",
        "select_cutter_tweak_tool": "Cycle Cutter Tweak",
        "updates": "Updates",
        "check_updates": "Check Updates",
        "update_addon": "Update",
        "update_status": "Status: {value}",
        "update_commits": "Branch: {branch} | Local: {current} | Remote: {remote}",
        "update_last_checked": "Last checked: {value}",
        "hide_all_sections": "Collapse All",
        "show_all_sections": "Expand All",
        "single_section_mode": "Single Mode",
        "rename_apply_weld": "Rename And Apply Weld",
        "rename_objects": "Rename Objects",
        "weld_distance": "Weld Distance",
        "apply_weld": "Apply Weld",
        "import_files": "Import Files",
        "format": "Format",
        "auto_rename_objects": "Auto Rename Objects",
        "folder": "Folder:",
        "no_folder_selected": "No folder selected",
        "total_files": "Total Files: {value}",
        "imported_files": "Imported Files: {value}",
        "imported_objects": "Imported Objects: {value}",
        "remaining_files": "Remaining Files: {value}",
        "current_file": "Current: {value}",
        "include_subfolders": "Include Subfolders",
        "scan_folder": "Scan Folder",
        "import_folder": "Import Folder",
        "quad_not_installed": "Quad Remesher add-on is not installed.",
        "quad_install_hint": "Install it to use these controls.",
        "quad_not_enabled": "Quad Remesher add-on is installed but not enabled.",
        "quad_enable_hint": "Enable it in Blender Preferences.",
        "quad_available": "Uses the installed Quad Remesher add-on.",
        "remesh_it": "Remesh It",
        "quad_count": "Quad Count",
        "use_materials": "Use Materials",
        "symmetry": "Symmetry:",
        "uvpackmaster_not_installed": "UVPackmaster 4 add-on is not installed.",
        "uvpackmaster_install_hint": "Install it to use these UV packing controls.",
        "uvpackmaster_not_enabled": "UVPackmaster 4 add-on is installed but not enabled.",
        "uvpackmaster_enable_hint": "Enable it in Blender Preferences.",
        "uvpackmaster_available": "Uses the installed UVPackmaster 4 add-on.",
        "uvpackmaster_pack": "PACK",
        "uvpackmaster_rotation_enable": "Rotation Enable",
        "uvpackmaster_margin": "Margin",
        "uvpackmaster_rotation_step": "Rotation Step",
        "uvpackmaster_heuristic_search": "Heuristic Search",
        "uvpackmaster_max_wait_time": "Max Wait Time (s)",
        "smooth_iterations": "Smooth Iterations",
        "smooth_face_selection": "Smooth Face Selection",
        "mark_selected_edges_seam": "Mark Selected Edges Seam",
        "mark_selection_boundary_seam": "Mark Selection Boundary Seam",
        "knife_seam": "Knife Seam",
        "quick_knife_seam": "Quick Knife Seam",
        "object_seam_cutter": "Object Seam Cutter",
        "stable_view_cut": "Stable View Cut",
        "xray": "X-Ray",
        "occlude_geometry": "Occlude Geometry",
        "only_selected": "Only Selected",
        "mark_as_seam": "Mark As Seam",
        "clear_selection_after_cutting": "Clear Selection After Cutting",
        "select_knife_tool": "Select Knife Seam Tool",
        "select_quick_knife_tool": "Select Quick Knife Seam Tool",
        "fill": "Fill",
        "threshold": "Threshold",
        "cutter_size": "Cutter Size",
        "cylinder_segments": "Cylinder Segments",
        "cutter_apply_method": "Apply Method",
        "cutter_alpha": "Cutter Alpha",
        "plane_thickness": "Plane Thickness",
        "path_render_u": "Path Render U",
        "path_extrude": "Path Extrude",
        "continue_path_cutters": "Continue Path Cutters",
        "path_join_distance": "Path Join Distance",
        "join_cutter_paths": "Join Selected Cutter Paths",
        "draw_point_distance": "Draw Point Distance",
        "draw_simplify_distance": "Draw Simplify",
        "continue_draw_strokes": "Continue Draw Strokes",
        "draw_join_distance": "Draw Join Distance",
        "auto_convert_draw_strokes": "Auto Convert Draw Strokes",
        "auto_convert_draw_strokes_on_apply": "Auto Convert Draw On Apply",
        "delete_draw_strokes_after_convert": "Delete Draw Strokes After Convert",
        "join_draw_strokes": "Join Selected Draw Strokes",
        "convert_draw_strokes_to_cutter_paths": "Convert Draw Strokes To Cutter Paths",
        "ctrl_draw_hint": "Ctrl + Click Draw",
        "hide_cutters_after_apply": "Hide Cutters After Apply",
        "delete_cutters_after_apply": "Delete Cutters After Apply",
        "select_draw_cutter_plane": "Select Draw Cutter Plane Tool",
        "draw_cutter_plane": "Draw Cutter Plane",
        "select_draw_cutter_arc": "Select Draw Cutter Arc Tool",
        "draw_cutter_arc": "Draw Cutter Arc",
        "select_draw_cutter_path": "Select Draw Cutter Path Tool",
        "draw_cutter_path": "Draw Cutter Path",
        "select_draw_cutter_draw": "Select Cutter Tweak Draw Tool",
        "draw_cutter_draw": "Cutter Tweak Draw",
        "tilt_minus": "-15 deg",
        "tilt_plus": "+15 deg",
        "apply_cutter_seams": "Apply Cutter Seams To Active",
        "split_object": "Split Object",
        "fill_cutter": "Fill Cutter",
        "select": "Select",
        "clear": "Clear",
        "last_cutters": "Last Cutters: {value}",
        "last_seam_edges": "Last Seam Edges: {value}",
        "material_mode": "Material Mode",
        "checker_scale": "Checker Scale",
        "generate_polygroups": "Generate PolyGroups",
        "apply_material_mode": "Apply Material Mode",
        "apply_checker_material": "Apply Checker Material",
        "generate_seams_materials": "Generate Seams From Materials",
        "unwrap_angle_based": "Unwrap Angle Based",
        "face_sets_to_materials": "Face Sets To Materials",
        "clear_polygroups_materials": "Clear PolyGroups Materials",
        "auto_unwrap": "Auto Unwrap",
        "prefer_backside_longitudinal_seam": "Prefer Backside Longitudinal Seam",
        "create_longitudinal_seam": "Create Longitudinal Seam",
        "boundary_longitudinal_seam": "Boundary + Longitudinal Seam",
        "smart_uv_project": "Smart UV Project",
        "average_islands_scale": "Average Islands Scale",
        "smart_decimate": "Smart Decimate",
        "ratio": "Ratio",
        "duplicate_and_apply_decimate": "Duplicate Object And Apply Decimate",
        "decimate": "Decimate",
        "check_mesh": "Check Mesh",
        "create_bkp": "Create BKP",
        "mesh_check_status": "Status: {value}",
        "mesh_check_normal_issues": "Normal issues: {value}",
        "mesh_check_inconsistent_normals": "Inconsistent normals: {value}",
        "mesh_check_inward_normals": "Possible inward normals: {value}",
        "mesh_check_ngons": "N-gons: {value}",
        "mesh_check_nonmanifold_edges": "Non-manifold edges: {value}",
        "mesh_check_boundary_edges": "Boundary/open edges: {value}",
        "mesh_check_boundary_loops": "Open boundary loops: {value}",
        "mesh_check_loose_geometry": "Loose geometry: {value}",
        "mesh_check_loose_vertices": "Loose vertices: {value}",
        "mesh_check_loose_edges": "Loose edges: {value}",
        "mesh_check_cleanup_issues": "Cleanup issues: {value}",
        "mesh_check_zero_area_faces": "Zero-area faces: {value}",
        "mesh_check_duplicate_vertices": "Duplicate vertices: {value}",
        "mesh_check_thin_protrusions": "Thin protrusion candidates: {value}",
        "fix_normals": "Fix Normals",
        "triangulate_ngons": "Triangulate N-gons",
        "fill_nonmanifold": "Fill Non-Manifold",
        "delete_loose": "Delete Loose",
        "select_thin_protrusions": "Select Protrusions",
        "delete_thin_protrusions": "Delete Protrusions",
        "clean_mesh": "Clean Mesh",
        "show_all_fix_operators": "Show/Hide All Fix Operators",
        "fab_rename": "FAB Rename",
        "fab_asset_name": "Asset Name",
        "fab_asset_index": "Index",
        "auto_increment_index": "Auto +1",
        "copy_textures": "Copy Textures",
        "fab_collection_color_tag": "Set Collection Color Tag",
        "auto_prepare_fab_selection": "Auto Prepare Selected FAB Set",
        "fab_rename_set_warning": "Do not forget to rename the set",
        "continue": "Continue",
        "mesh_export": "Export",
        "mesh_export_format": "Format",
        "export_selected_meshes": "Export Selected Meshes",
        "blend_asset_export": "Export .blend Assets",
        "blend_export_directory": "Output",
        "blend_export_static_collection_picker": "Add Static",
        "blend_export_static_collections": "Static Collections",
        "blend_export_individual_assets": "Individual asset collections",
        "blend_export_all_low": "All LOW",
        "blend_export_all_mid": "All MID",
        "blend_export_include_render_settings": "World/Render Settings",
        "blend_export_overwrite_existing": "Overwrite Existing",
        "blend_export_scan": "Scan Blend Assets",
        "blend_export_start": "Export Blend Assets",
        "blend_export_status": "Status: {value}",
        "blend_export_collections": "Collections: {value}",
        "blend_export_files": "Files: {value}",
        "blend_export_low": "LOW: {value}",
        "blend_export_mid": "MID: {value}",
        "render_scan_queue": "Scan Queue",
        "render_start": "Start Render",
        "render_continue": "Continue",
        "render_stop": "Stop",
        "render_engine": "Engine",
        "render_max_samples": "Max Samples",
        "render_resolution_x": "Resolution X",
        "render_resolution_y": "Resolution Y",
        "render_resolution_scale": "Resolution Scale",
        "render_output_directory": "Output",
        "render_low": "LOW",
        "render_mid": "MID",
        "render_transparent_background": "Transparent Background",
        "render_scene_collection_prefix": "Scene Prefix",
        "render_multiview": "Multi View",
        "render_multiview_offset": "View Offset",
        "render_clear_multiview": "Clear Multi View",
        "render_freestyle_edges": "Freestyle Edges",
        "render_freestyle_as_pass": "As Render Pass",
        "render_freestyle_thickness": "Line Thickness",
        "render_freestyle_color": "Line Color",
        "render_mark_freestyle": "Mark Freestyle",
        "render_clear_freestyle": "Clear Freestyle",
        "render_skip_existing": "Skip Existing",
        "render_overwrite_existing": "Overwrite Existing",
        "render_status": "Status: {value}",
        "render_collections": "Collections: {value}",
        "render_queued": "Queued: {value}",
        "render_rendered": "Rendered: {value}",
        "render_remaining": "Remaining: {value}",
        "render_current": "Current: {collection} / {object}",
        "render_last_output": "Last Output: {value}",
        "bake_resolution": "Bake Resolution",
        "bake_margin": "Bake Margin",
        "cage_extrusion": "Cage Extrusion",
        "ray_distance": "Ray Distance",
        "image_prefix": "Image Prefix",
        "selected_to_active": "Selected To Active",
        "base_color": "Base Color",
        "normal": "Normal",
        "auto_save_textures_after_bake": "Auto Save Textures After Bake",
        "check_material_textures": "Check Material/Textures",
        "prepare_highpoly_texture_only": "Prepare Highpoly Texture Only",
        "prepare_lowpoly_bake_material": "Prepare Lowpoly Bake Material",
        "bake_selected_to_active": "Bake Selected To Active",
        "prepare_and_bake": "Prepare And Bake",
        "save_textures": "Save Textures",
        "merge_materials_textures": "Merge Materials/Textures",
        "clear_all_bake_images": "Clear All Bake Images",
        "multires_levels": "Multires Levels",
        "shrinkwrap_limit": "Shrinkwrap Limit",
        "shrinkwrap_offset": "Shrinkwrap Offset",
        "setup_resculpting": "Setup Resculpting",
        "multires": "Multires",
        "shrinkwrap": "Shrinkwrap",
        "material_source_texture": "Source Texture",
        "material_texture_color": "Texture + Color",
        "material_random_color": "Random Color",
        "material_checker_texture": "Checker Texture",
        "format_auto": "Auto",
        "ai_prompt": "Prompt",
        "ai_model": "Model",
        "ai_size": "Size",
        "ai_quality": "Quality",
        "ai_aspect_ratio": "Aspect Ratio",
        "ai_image_size": "Image Size",
        "ai_output_format": "Output Format",
        "ai_input_image": "Input Image",
        "select_base_color_image": "Select Base Color Image",
        "select_normal_map_image": "Select Normal Map Image",
        "preview_input_image": "Preview Input",
        "generate_openai_image": "Generate OpenAI Image",
        "generate_google_image": "Generate Google Image",
        "open_image_editor": "Open In Image Editor",
        "save_image": "Save Image",
        "ai_status": "Status: {value}",
        "ai_last_image": "Last Image: {value}",
        "ai_no_status": "Ready",
        "ai_key_missing": "OpenAI API key is missing. Add it in preferences or set OPENAI_API_KEY.",
        "google_key_missing": "Google Gemini API key is missing. Add it in preferences or set GEMINI_API_KEY.",
        "ai_generating": "Generating image...",
        "prompt_library": "Prompt Library",
        "prompt_collection": "Collection",
        "prompt_file": "Prompt",
        "load_to_openai": "Load OpenAI",
        "load_to_google": "Load Google",
        "load_to_both": "Load Both",
        "append_to_openai": "Append OpenAI",
        "append_to_google": "Append Google",
        "refresh_prompt_library": "Refresh",
        "open_prompt_folder": "Open Folder",
    },
    "RU": {
        "language": "Язык",
        "main_description": "Инструменты полуавтоматической ретопологии для AI-мешей",
        "preferences_info": "Инфо",
        "preferences_language": "Настройки языка",
        "preferences_operations": "Операции",
        "preferences_api": "API",
        "preferences_pie_menu": "Настройки Pie Menu",
        "addon_name": "Название: {value}",
        "addon_version": "Версия: {value}",
        "addon_author": "Автор: {value}",
        "addon_contact": "Контакт: {value}",
        "addon_github": "GitHub: {value}",
        "open_link": "Открыть",
        "show_panel_settings": "Показывать настройки в панели",
        "play_sound_after_operations": "Воспроизводить звук по окончании операций",
        "section_import": "Импорт",
        "section_batch_import": "Пакетный импорт",
        "section_model_preparation": "Подготовка модели",
        "section_seam_preparation": "Подготовка швов",
        "section_polygroups": "Полигруппы",
        "section_remesh": "Ремеш",
        "section_resculpting": "Рескульптинг",
        "section_seam_finalization": "Финализация швов",
        "section_uv_preparation": "UV подготовка",
        "section_baking": "Бейкинг",
        "section_ai_generation": "AI-генерация",
        "section_mesh_finalization": "Финализация меша",
        "section_render": "Рендер",
        "openai_image": "OpenAI Image",
        "google_image": "Google Image",
        "use_env_openai_api_key": "Использовать OPENAI_API_KEY",
        "openai_api_key": "OpenAI API Key",
        "use_env_gemini_api_key": "Использовать GEMINI_API_KEY",
        "gemini_api_key": "Google Gemini API Key",
        "hotkeys": "Горячие клавиши",
        "cutter_tweak_tool": "Стартовый Cutter Tweak",
        "enable_cutter_tweak_hotkey": "Включить хоткей Cutter Tweak",
        "enable_pie_menu_hotkey": "Включить хоткей кругового меню",
        "hotkey_key": "Клавиша",
        "pie_menu_slots": "Слоты кругового меню",
        "pie_slot": "Слот {index}",
        "select_cutter_tweak_tool": "Переключить Cutter Tweak",
        "updates": "Обновления",
        "check_updates": "Проверить обновления",
        "update_addon": "Обновить",
        "update_status": "Статус: {value}",
        "update_commits": "Ветка: {branch} | Локально: {current} | Удаленно: {remote}",
        "update_last_checked": "Последняя проверка: {value}",
        "hide_all_sections": "Свернуть все",
        "show_all_sections": "Развернуть все",
        "single_section_mode": "Single Mode",
        "rename_apply_weld": "Переименовать и применить Weld",
        "rename_objects": "Переименовать объекты",
        "weld_distance": "Дистанция Weld",
        "apply_weld": "Применить Weld",
        "import_files": "Импорт файлов",
        "format": "Формат",
        "auto_rename_objects": "Автопереименование",
        "folder": "Папка:",
        "no_folder_selected": "Папка не выбрана",
        "total_files": "Всего файлов: {value}",
        "imported_files": "Импортировано файлов: {value}",
        "imported_objects": "Импортировано объектов: {value}",
        "remaining_files": "Осталось файлов: {value}",
        "current_file": "Текущий: {value}",
        "include_subfolders": "Учитывать подпапки",
        "scan_folder": "Сканировать папку",
        "import_folder": "Импорт папки",
        "quad_not_installed": "Аддон Quad Remesher не установлен.",
        "quad_install_hint": "Установите его, чтобы использовать эти функции.",
        "quad_not_enabled": "Аддон Quad Remesher установлен, но не включен.",
        "quad_enable_hint": "Включите его в настройках Blender.",
        "quad_available": "Используется установленный аддон Quad Remesher.",
        "remesh_it": "Запустить ремеш",
        "quad_count": "Количество квадов",
        "use_materials": "Использовать материалы",
        "symmetry": "Симметрия:",
        "uvpackmaster_not_installed": "Аддон UVPackmaster 4 не установлен.",
        "uvpackmaster_install_hint": "Установите его, чтобы использовать эти настройки UV-упаковки.",
        "uvpackmaster_not_enabled": "Аддон UVPackmaster 4 установлен, но не включен.",
        "uvpackmaster_enable_hint": "Включите его в настройках Blender.",
        "uvpackmaster_available": "Используется установленный аддон UVPackmaster 4.",
        "uvpackmaster_pack": "PACK",
        "uvpackmaster_rotation_enable": "Rotation Enable",
        "uvpackmaster_margin": "Margin",
        "uvpackmaster_rotation_step": "Rotation Step",
        "uvpackmaster_heuristic_search": "Heuristic Search",
        "uvpackmaster_max_wait_time": "Max Wait Time (s)",
        "smooth_iterations": "Итерации сглаживания",
        "smooth_face_selection": "Сгладить выделение фейсов",
        "mark_selected_edges_seam": "Пометить выделенные ребра как швы",
        "mark_selection_boundary_seam": "Шов по границе выделения",
        "knife_seam": "Knife Seam",
        "quick_knife_seam": "Quick Knife Seam",
        "object_seam_cutter": "Object Seam Cutter",
        "stable_view_cut": "Стабильный рез из вида",
        "xray": "X-Ray",
        "occlude_geometry": "Только видимая геометрия",
        "only_selected": "Только выделенное",
        "mark_as_seam": "Пометить как шов",
        "clear_selection_after_cutting": "Снять выделение после реза",
        "select_knife_tool": "Выбрать Knife Seam",
        "select_quick_knife_tool": "Выбрать Quick Knife Seam",
        "fill": "Заполнить",
        "threshold": "Порог",
        "cutter_size": "Размер каттера",
        "cylinder_segments": "Сегменты цилиндра",
        "cutter_apply_method": "Метод",
        "cutter_alpha": "Прозрачность каттера",
        "plane_thickness": "Толщина плоскости",
        "path_render_u": "Render U пути",
        "path_extrude": "Толщина пути",
        "continue_path_cutters": "Продолжать Cutter Paths",
        "path_join_distance": "Дистанция склейки Path",
        "join_cutter_paths": "Склеить выбранные Cutter Paths",
        "draw_point_distance": "Дистанция точек Draw",
        "draw_simplify_distance": "Упрощение Draw",
        "continue_draw_strokes": "Продолжать Draw strokes",
        "draw_join_distance": "Дистанция склейки Draw",
        "auto_convert_draw_strokes": "Автоконвертация Draw strokes",
        "auto_convert_draw_strokes_on_apply": "Автоконвертация Draw при Apply",
        "delete_draw_strokes_after_convert": "Удалять Draw strokes после конвертации",
        "join_draw_strokes": "Склеить выбранные Draw strokes",
        "convert_draw_strokes_to_cutter_paths": "Конвертировать Draw strokes в Cutter Paths",
        "ctrl_draw_hint": "Ctrl + Click рисует",
        "hide_cutters_after_apply": "Скрыть каттеры после применения",
        "delete_cutters_after_apply": "Удалить каттеры после применения",
        "select_draw_cutter_plane": "Выбрать Draw Cutter Plane",
        "draw_cutter_plane": "Нарисовать cutter plane",
        "select_draw_cutter_arc": "Выбрать Draw Cutter Arc",
        "draw_cutter_arc": "Нарисовать cutter arc",
        "select_draw_cutter_path": "Выбрать Draw Cutter Path",
        "draw_cutter_path": "Нарисовать cutter path",
        "select_draw_cutter_draw": "Выбрать Cutter Tweak Draw",
        "draw_cutter_draw": "Cutter Tweak Draw",
        "tilt_minus": "-15 deg",
        "tilt_plus": "+15 deg",
        "apply_cutter_seams": "Применить cutter seams к активному",
        "split_object": "Разделить объект",
        "fill_cutter": "Fill Cutter",
        "select": "Выбрать",
        "clear": "Очистить",
        "last_cutters": "Последние каттеры: {value}",
        "last_seam_edges": "Последние швы: {value}",
        "material_mode": "Режим материала",
        "checker_scale": "Масштаб checker",
        "generate_polygroups": "Сгенерировать полигруппы",
        "apply_material_mode": "Применить режим материалов",
        "apply_checker_material": "Применить checker material",
        "generate_seams_materials": "Создать швы по материалам",
        "unwrap_angle_based": "Развертка Angle Based",
        "face_sets_to_materials": "Face Sets в материалы",
        "clear_polygroups_materials": "Очистить материалы полигрупп",
        "auto_unwrap": "Авторазвертка",
        "prefer_backside_longitudinal_seam": "Стараться делать продольный шов сзади",
        "create_longitudinal_seam": "Создать продольный шов",
        "boundary_longitudinal_seam": "Граница + продольный шов",
        "smart_uv_project": "Smart UV Project",
        "average_islands_scale": "Выровнять масштаб островов",
        "smart_decimate": "Умный децимейт",
        "ratio": "Ратио",
        "duplicate_and_apply_decimate": "Дублировать объект и применить децимейт",
        "decimate": "Децимейт",
        "check_mesh": "Проверка меша",
        "create_bkp": "Create BKP",
        "mesh_check_status": "Статус: {value}",
        "mesh_check_normal_issues": "Проблемы нормалей: {value}",
        "mesh_check_inconsistent_normals": "Несогласованные нормали: {value}",
        "mesh_check_inward_normals": "Возможные вывернутые нормали: {value}",
        "mesh_check_ngons": "N-gons: {value}",
        "mesh_check_nonmanifold_edges": "Non-manifold ребра: {value}",
        "mesh_check_boundary_edges": "Открытые/граничные ребра: {value}",
        "mesh_check_boundary_loops": "Открытые контуры: {value}",
        "mesh_check_loose_geometry": "Loose геометрия: {value}",
        "mesh_check_loose_vertices": "Loose вершины: {value}",
        "mesh_check_loose_edges": "Loose ребра: {value}",
        "mesh_check_cleanup_issues": "Ошибки очистки: {value}",
        "mesh_check_zero_area_faces": "Фейсы с нулевой площадью: {value}",
        "mesh_check_duplicate_vertices": "Дублированные вершины: {value}",
        "mesh_check_thin_protrusions": "Торчащие тонкие полигоны: {value}",
        "fix_normals": "Fix Normals",
        "triangulate_ngons": "Triangulate N-gons",
        "fill_nonmanifold": "Fill Non-Manifold",
        "delete_loose": "Delete Loose",
        "select_thin_protrusions": "Выделить торчащие",
        "delete_thin_protrusions": "Удалить торчащие",
        "clean_mesh": "Clean Mesh",
        "show_all_fix_operators": "Show/Hide All Fix Operators",
        "fab_rename": "Переименование FAB",
        "fab_asset_name": "Имя объекта",
        "fab_asset_index": "Индекс",
        "auto_increment_index": "Авто +1",
        "copy_textures": "Копировать текстуры",
        "fab_collection_color_tag": "Цвет коллекции",
        "auto_prepare_fab_selection": "Автоподготовка выбранного FAB-набора",
        "fab_rename_set_warning": "Не забудьте переименовать сет",
        "continue": "Продолжить",
        "mesh_export": "Экспорт",
        "mesh_export_format": "Формат",
        "export_selected_meshes": "Экспорт выделенных мешей",
        "blend_asset_export": "Экспорт .blend ассетов",
        "blend_export_directory": "Папка",
        "blend_export_static_collection_picker": "Добавить static",
        "blend_export_static_collections": "Статические коллекции",
        "blend_export_individual_assets": "Отдельные asset-коллекции",
        "blend_export_all_low": "Все LOW",
        "blend_export_all_mid": "Все MID",
        "blend_export_include_render_settings": "World/Render настройки",
        "blend_export_overwrite_existing": "Перезаписывать файлы",
        "blend_export_scan": "Сканировать .blend ассеты",
        "blend_export_start": "Экспорт .blend ассетов",
        "blend_export_status": "Статус: {value}",
        "blend_export_collections": "Коллекций: {value}",
        "blend_export_files": "Файлов: {value}",
        "blend_export_low": "LOW: {value}",
        "blend_export_mid": "MID: {value}",
        "render_scan_queue": "Сканировать очередь",
        "render_start": "Старт рендера",
        "render_continue": "Продолжить",
        "render_stop": "Стоп",
        "render_engine": "Движок",
        "render_max_samples": "Max samples",
        "render_resolution_x": "Разрешение X",
        "render_resolution_y": "Разрешение Y",
        "render_resolution_scale": "Масштаб разрешения",
        "render_output_directory": "Папка",
        "render_low": "LOW",
        "render_mid": "MID",
        "render_transparent_background": "Прозрачный фон",
        "render_scene_collection_prefix": "Префикс сцены",
        "render_multiview": "Multi View",
        "render_multiview_offset": "Сдвиг видов",
        "render_clear_multiview": "Очистить Multi View",
        "render_freestyle_edges": "Freestyle Edges",
        "render_freestyle_as_pass": "As Render Pass",
        "render_freestyle_thickness": "Толщина линий",
        "render_freestyle_color": "Цвет линий",
        "render_mark_freestyle": "Пометить Freestyle",
        "render_clear_freestyle": "Очистить Freestyle",
        "render_skip_existing": "Пропускать готовые",
        "render_overwrite_existing": "Перезаписывать",
        "render_status": "Статус: {value}",
        "render_collections": "Коллекций: {value}",
        "render_queued": "В очереди: {value}",
        "render_rendered": "Отрендерено: {value}",
        "render_remaining": "Осталось: {value}",
        "render_current": "Текущий: {collection} / {object}",
        "render_last_output": "Последний файл: {value}",
        "bake_resolution": "Разрешение bake",
        "bake_margin": "Отступ bake",
        "cage_extrusion": "Cage Extrusion",
        "ray_distance": "Ray Distance",
        "image_prefix": "Префикс изображений",
        "selected_to_active": "Selected To Active",
        "base_color": "Base Color",
        "normal": "Normal",
        "auto_save_textures_after_bake": "Автосохранение текстур после запекания",
        "check_material_textures": "Проверить материалы/текстуры",
        "prepare_highpoly_texture_only": "Highpoly в Texture Only",
        "prepare_lowpoly_bake_material": "Подготовить материал lowpoly",
        "bake_selected_to_active": "Запечь выделенное на активный",
        "prepare_and_bake": "Подготовить и запечь",
        "save_textures": "Сохранить текстуры",
        "merge_materials_textures": "Объединить материалы/текстуры",
        "clear_all_bake_images": "Очистить все bake images",
        "multires_levels": "Уровни Multires",
        "shrinkwrap_limit": "Лимит Shrinkwrap",
        "shrinkwrap_offset": "Смещение Shrinkwrap",
        "setup_resculpting": "Настроить рескульптинг",
        "multires": "Multires",
        "shrinkwrap": "Shrinkwrap",
        "material_source_texture": "Исходная текстура",
        "material_texture_color": "Текстура + цвет",
        "material_random_color": "Случайный цвет",
        "material_checker_texture": "Checker Texture",
        "format_auto": "Авто",
        "ai_prompt": "Промпт",
        "ai_model": "Модель",
        "ai_size": "Размер",
        "ai_quality": "Качество",
        "ai_aspect_ratio": "Соотношение сторон",
        "ai_image_size": "Размер изображения",
        "ai_output_format": "Формат",
        "ai_input_image": "Input Image",
        "select_base_color_image": "Выбрать Base Color Image",
        "select_normal_map_image": "Выбрать Normal Map Image",
        "preview_input_image": "Preview Input",
        "generate_openai_image": "Сгенерировать OpenAI изображение",
        "generate_google_image": "Сгенерировать Google изображение",
        "open_image_editor": "Открыть в Image Editor",
        "save_image": "Сохранить изображение",
        "ai_status": "Статус: {value}",
        "ai_last_image": "Последнее изображение: {value}",
        "ai_no_status": "Готово",
        "ai_key_missing": "OpenAI API key не найден. Добавьте его в настройках или задайте OPENAI_API_KEY.",
        "google_key_missing": "Google Gemini API key не найден. Добавьте его в настройках или задайте GEMINI_API_KEY.",
        "ai_generating": "Генерация изображения...",
        "prompt_library": "Библиотека промптов",
        "prompt_collection": "Коллекция",
        "prompt_file": "Промпт",
        "load_to_openai": "Загрузить OpenAI",
        "load_to_google": "Загрузить Google",
        "load_to_both": "Загрузить в обе",
        "append_to_openai": "Добавить OpenAI",
        "append_to_google": "Добавить Google",
        "refresh_prompt_library": "Обновить",
        "open_prompt_folder": "Открыть папку",
    },
}


def get_preferences(context):
    if context is None:
        return None

    addon = context.preferences.addons.get(__package__)
    if addon is None:
        return None
    return addon.preferences


def get_language(context):
    preferences = get_preferences(context)
    if preferences is None:
        return "EN"
    return getattr(preferences, "interface_language", "EN")


def t(context, key, **kwargs):
    language = get_language(context)
    value = TEXT.get(language, TEXT["EN"]).get(key, TEXT["EN"].get(key, key))
    if kwargs:
        return value.format(**kwargs)
    return value
