from .apply_weld import OBJECT_OT_polygroups_apply_weld
from .ai_generation import OBJECT_OT_airetopo_generate_google_image
from .ai_generation import OBJECT_OT_airetopo_generate_openai_image
from .ai_generation import OBJECT_OT_airetopo_load_library_prompt
from .ai_generation import OBJECT_OT_airetopo_open_generated_image
from .ai_generation import OBJECT_OT_airetopo_open_prompt_library_folder
from .ai_generation import OBJECT_OT_airetopo_preview_input_image
from .ai_generation import OBJECT_OT_airetopo_refresh_prompt_library
from .ai_generation import OBJECT_OT_airetopo_save_generated_image
from .ai_generation import OBJECT_OT_airetopo_select_material_image
from .baking import OBJECT_OT_polygroups_bake_selected_to_active
from .baking import OBJECT_OT_polygroups_calculate_auto_cage
from .baking import OBJECT_OT_polygroups_clear_bake_temp_images
from .baking import OBJECT_OT_polygroups_merge_bake_textures
from .baking import OBJECT_OT_polygroups_prepare_and_bake
from .baking import OBJECT_OT_polygroups_prepare_highpoly_bake_materials
from .baking import OBJECT_OT_polygroups_prepare_lowpoly_bake_material
from .baking import OBJECT_OT_polygroups_save_blend_file
from .baking import OBJECT_OT_polygroups_save_blend_file_as
from .baking import OBJECT_OT_polygroups_save_bake_textures
from .batch_import import OBJECT_OT_polygroups_batch_import
from .batch_import import OBJECT_OT_polygroups_arrange_batch_objects
from .batch_import import OBJECT_OT_polygroups_scan_import_folder
from .batch_import import OBJECT_OT_polygroups_select_import_folder
from .check_material_textures import OBJECT_OT_polygroups_check_material_textures
from .clear_materials import OBJECT_OT_clear_polygroups_materials
from .face_sets_to_materials import OBJECT_OT_face_sets_to_materials
from .fab_preparation import OBJECT_OT_polygroups_auto_prepare_fab_selection
from .fab_preparation import OBJECT_OT_polygroups_prepare_fab_variant
from .generate_polygroups import OBJECT_OT_generate_polygroups
from .generate_polygroups import OBJECT_OT_polygroups_apply_checker_material
from .generate_polygroups import OBJECT_OT_polygroups_apply_material_mode
from .knife_seam_tool import MESH_OT_polygroups_knife_seam
from .mark_material_boundaries_seam import MESH_OT_polygroups_mark_material_boundaries_seam
from .mark_longitudinal_seam import MESH_OT_polygroups_mark_boundary_and_longitudinal_seam
from .mark_longitudinal_seam import MESH_OT_polygroups_mark_longitudinal_seam
from .mark_selection_boundary_seam import MESH_OT_polygroups_mark_selection_boundary_seam
from .mark_selected_edges_seam import MESH_OT_polygroups_mark_selected_edges_seam
from .mesh_checks import OBJECT_OT_polygroups_check_mesh
from .mesh_checks import OBJECT_OT_polygroups_clean_mesh
from .mesh_checks import OBJECT_OT_polygroups_create_mesh_backup
from .mesh_checks import OBJECT_OT_polygroups_delete_loose_geometry
from .mesh_checks import OBJECT_OT_polygroups_delete_thin_protrusions
from .mesh_checks import OBJECT_OT_polygroups_fill_nonmanifold
from .mesh_checks import OBJECT_OT_polygroups_fix_mesh_normals
from .mesh_checks import OBJECT_OT_polygroups_select_thin_protrusions
from .mesh_checks import OBJECT_OT_polygroups_triangulate_ngons
from .mesh_export import OBJECT_OT_polygroups_export_blend_assets
from .mesh_export import OBJECT_OT_polygroups_export_selected_meshes
from .mesh_export import OBJECT_OT_polygroups_add_blend_static_collection
from .mesh_export import OBJECT_OT_polygroups_clear_blend_static_collections
from .mesh_export import OBJECT_OT_polygroups_scan_blend_assets
from .object_seam_cutter import OBJECT_OT_polygroups_apply_cutter_seams
from .object_seam_cutter import OBJECT_OT_polygroups_bezier_cutter_paths
from .object_seam_cutter import OBJECT_OT_polygroups_clear_cutter_planes
from .object_seam_cutter import OBJECT_OT_polygroups_convert_draw_strokes_to_cutter_paths
from .object_seam_cutter import OBJECT_OT_polygroups_copy_mirror_cutters
from .object_seam_cutter import OBJECT_OT_polygroups_draw_cutter_arc
from .object_seam_cutter import OBJECT_OT_polygroups_draw_cutter_draw
from .object_seam_cutter import OBJECT_OT_polygroups_draw_cutter_local_ring
from .object_seam_cutter import OBJECT_OT_polygroups_draw_cutter_path
from .object_seam_cutter import OBJECT_OT_polygroups_draw_cutter_plane
from .object_seam_cutter import OBJECT_OT_polygroups_join_draw_strokes
from .object_seam_cutter import OBJECT_OT_polygroups_join_cutter_paths
from .object_seam_cutter import OBJECT_OT_polygroups_select_cutter_planes
from .object_seam_cutter import OBJECT_OT_polygroups_split_object_by_cutters
from .object_seam_cutter import OBJECT_OT_polygroups_smooth_cutter_path_tilt
from .object_seam_cutter import OBJECT_OT_polygroups_smooth_cutter_paths
from .object_seam_cutter import OBJECT_OT_polygroups_tilt_cutter_path
from .object_seam_cutter import OBJECT_OT_polygroups_toggle_cyclic_cutter_paths
from .panel_visibility import OBJECT_OT_airetopo_set_all_section_visibility
from .quick_knife_seam_tool import MESH_OT_polygroups_quick_knife_seam
from .rename_objects import OBJECT_OT_polygroups_rename_objects
from .remesh_presets import OBJECT_OT_polygroups_set_quad_count_preset
from .render_queue import OBJECT_OT_polygroups_clear_multiview_render
from .render_queue import OBJECT_OT_polygroups_clear_freestyle_edges
from .render_queue import OBJECT_OT_polygroups_continue_render_queue
from .render_queue import OBJECT_OT_polygroups_mark_freestyle_edges
from .render_queue import OBJECT_OT_polygroups_render_current_state
from .render_queue import OBJECT_OT_polygroups_scan_render_queue
from .render_queue import OBJECT_OT_polygroups_start_render_queue
from .render_queue import OBJECT_OT_polygroups_stop_render_queue
from .resculpting import OBJECT_OT_polygroups_add_multires
from .resculpting import OBJECT_OT_polygroups_add_shrinkwrap_to_highpoly
from .resculpting import OBJECT_OT_polygroups_setup_resculpting
from .select_seam_tool import MESH_OT_polygroups_select_seam_tool
from .safety_checks import OBJECT_OT_polygroups_checked_quad_remesh
from .safety_checks import OBJECT_OT_polygroups_checked_generate_polygroups
from .safety_checks import OBJECT_OT_polygroups_checked_prepare_and_bake
from .safety_checks import OBJECT_OT_polygroups_checked_prepare_lowpoly_bake_material
from .safety_checks import OBJECT_OT_polygroups_make_lowpoly_active
from .safety_checks import OBJECT_OT_polygroups_rename_and_apply_weld
from .safety_checks import OBJECT_OT_polygroups_skip_prepare_and_bake
from .safety_checks import OBJECT_OT_polygroups_skip_generate_polygroups
from .safety_checks import OBJECT_OT_polygroups_skip_quad_remesh
from .smooth_face_selection import MESH_OT_polygroups_smooth_face_selection
from .smart_decimate import OBJECT_OT_polygroups_smart_decimate
from .unwrap_angle_based import OBJECT_OT_polygroups_average_islands_scale
from .unwrap_angle_based import OBJECT_OT_polygroups_smart_uv_project
from .unwrap_angle_based import OBJECT_OT_polygroups_unwrap_angle_based
from .uvpackmaster_controls import OBJECT_OT_polygroups_uvpackmaster_pack

CLASSES = (
    OBJECT_OT_polygroups_apply_weld,
    OBJECT_OT_polygroups_select_import_folder,
    OBJECT_OT_airetopo_generate_openai_image,
    OBJECT_OT_airetopo_generate_google_image,
    OBJECT_OT_airetopo_refresh_prompt_library,
    OBJECT_OT_airetopo_open_prompt_library_folder,
    OBJECT_OT_airetopo_load_library_prompt,
    OBJECT_OT_airetopo_select_material_image,
    OBJECT_OT_airetopo_preview_input_image,
    OBJECT_OT_airetopo_open_generated_image,
    OBJECT_OT_airetopo_save_generated_image,
    OBJECT_OT_airetopo_set_all_section_visibility,
    OBJECT_OT_polygroups_scan_import_folder,
    OBJECT_OT_polygroups_batch_import,
    OBJECT_OT_polygroups_arrange_batch_objects,
    OBJECT_OT_polygroups_rename_objects,
    OBJECT_OT_polygroups_check_material_textures,
    OBJECT_OT_polygroups_prepare_highpoly_bake_materials,
    OBJECT_OT_polygroups_prepare_lowpoly_bake_material,
    OBJECT_OT_polygroups_calculate_auto_cage,
    OBJECT_OT_polygroups_bake_selected_to_active,
    OBJECT_OT_polygroups_prepare_and_bake,
    OBJECT_OT_polygroups_save_blend_file,
    OBJECT_OT_polygroups_save_blend_file_as,
    OBJECT_OT_polygroups_save_bake_textures,
    OBJECT_OT_polygroups_merge_bake_textures,
    OBJECT_OT_polygroups_clear_bake_temp_images,
    OBJECT_OT_polygroups_add_multires,
    OBJECT_OT_polygroups_add_shrinkwrap_to_highpoly,
    OBJECT_OT_polygroups_setup_resculpting,
    OBJECT_OT_polygroups_rename_and_apply_weld,
    OBJECT_OT_polygroups_checked_quad_remesh,
    OBJECT_OT_polygroups_checked_generate_polygroups,
    OBJECT_OT_polygroups_checked_prepare_lowpoly_bake_material,
    OBJECT_OT_polygroups_checked_prepare_and_bake,
    OBJECT_OT_polygroups_skip_quad_remesh,
    OBJECT_OT_polygroups_skip_generate_polygroups,
    OBJECT_OT_polygroups_skip_prepare_and_bake,
    OBJECT_OT_polygroups_make_lowpoly_active,
    OBJECT_OT_polygroups_set_quad_count_preset,
    OBJECT_OT_polygroups_render_current_state,
    OBJECT_OT_polygroups_scan_render_queue,
    OBJECT_OT_polygroups_start_render_queue,
    OBJECT_OT_polygroups_stop_render_queue,
    OBJECT_OT_polygroups_clear_multiview_render,
    OBJECT_OT_polygroups_mark_freestyle_edges,
    OBJECT_OT_polygroups_clear_freestyle_edges,
    OBJECT_OT_polygroups_continue_render_queue,
    OBJECT_OT_generate_polygroups,
    OBJECT_OT_polygroups_apply_checker_material,
    OBJECT_OT_polygroups_apply_material_mode,
    MESH_OT_polygroups_mark_material_boundaries_seam,
    OBJECT_OT_polygroups_unwrap_angle_based,
    OBJECT_OT_polygroups_smart_uv_project,
    OBJECT_OT_polygroups_average_islands_scale,
    OBJECT_OT_polygroups_uvpackmaster_pack,
    OBJECT_OT_face_sets_to_materials,
    OBJECT_OT_clear_polygroups_materials,
    OBJECT_OT_polygroups_prepare_fab_variant,
    OBJECT_OT_polygroups_auto_prepare_fab_selection,
    MESH_OT_polygroups_mark_boundary_and_longitudinal_seam,
    MESH_OT_polygroups_mark_longitudinal_seam,
    MESH_OT_polygroups_mark_selected_edges_seam,
    MESH_OT_polygroups_mark_selection_boundary_seam,
    MESH_OT_polygroups_smooth_face_selection,
    OBJECT_OT_polygroups_check_mesh,
    OBJECT_OT_polygroups_fix_mesh_normals,
    OBJECT_OT_polygroups_triangulate_ngons,
    OBJECT_OT_polygroups_fill_nonmanifold,
    OBJECT_OT_polygroups_delete_loose_geometry,
    OBJECT_OT_polygroups_select_thin_protrusions,
    OBJECT_OT_polygroups_delete_thin_protrusions,
    OBJECT_OT_polygroups_clean_mesh,
    OBJECT_OT_polygroups_create_mesh_backup,
    OBJECT_OT_polygroups_export_selected_meshes,
    OBJECT_OT_polygroups_scan_blend_assets,
    OBJECT_OT_polygroups_add_blend_static_collection,
    OBJECT_OT_polygroups_clear_blend_static_collections,
    OBJECT_OT_polygroups_export_blend_assets,
    MESH_OT_polygroups_knife_seam,
    MESH_OT_polygroups_quick_knife_seam,
    MESH_OT_polygroups_select_seam_tool,
    OBJECT_OT_polygroups_smart_decimate,
    OBJECT_OT_polygroups_draw_cutter_plane,
    OBJECT_OT_polygroups_draw_cutter_arc,
    OBJECT_OT_polygroups_draw_cutter_local_ring,
    OBJECT_OT_polygroups_draw_cutter_path,
    OBJECT_OT_polygroups_draw_cutter_draw,
    OBJECT_OT_polygroups_convert_draw_strokes_to_cutter_paths,
    OBJECT_OT_polygroups_join_draw_strokes,
    OBJECT_OT_polygroups_join_cutter_paths,
    OBJECT_OT_polygroups_bezier_cutter_paths,
    OBJECT_OT_polygroups_toggle_cyclic_cutter_paths,
    OBJECT_OT_polygroups_smooth_cutter_paths,
    OBJECT_OT_polygroups_smooth_cutter_path_tilt,
    OBJECT_OT_polygroups_tilt_cutter_path,
    OBJECT_OT_polygroups_copy_mirror_cutters,
    OBJECT_OT_polygroups_apply_cutter_seams,
    OBJECT_OT_polygroups_split_object_by_cutters,
    OBJECT_OT_polygroups_select_cutter_planes,
    OBJECT_OT_polygroups_clear_cutter_planes,
)


def register():
    import bpy

    for cls in CLASSES:
        bpy.utils.register_class(cls)


def unregister():
    import bpy

    for cls in reversed(CLASSES):
        bpy.utils.unregister_class(cls)
